routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use App\Cart;
use App\OrderingTime;
use App\ProductColor;
use Illuminate\Http\Request;

Route::prefix('admin')->middleware(['auth','admin'])->group(function (){

    Route::get('/','Admin\AdminController@index')->name('admin');
    Route::get('/panel','Admin\AdminController@author_panel')->name('author_panel');
    Route::get('/403','Admin\AdminController@error403')->name('error403');
    Route::get('filemanager','Admin\AdminController@filemanager')->name('filemanager');
    Route::get('payments', 'Admin\AdminController@payments')->name('payments');
    create_crud_route('category','CategoryController');
    create_crud_route('brands','BrandController');
    create_crud_route('colors','ColorController');
    create_crud_route('products','ProductController',[]);
    create_crud_route('warranties','WarrantyController');
    create_crud_route('product_warranties','ProductWarrantyController');
    create_crud_route('sliders','SliderController');
    create_crud_route('province','ProvinceController');
    create_crud_route('city','CityController');
    create_crud_route('discount','DiscountController');
    create_crud_route('commissions','CommissionController');
    create_crud_route('pages','PageController');

    create_crud_route('category-common-question','CategoryCommonQuestionController');
    create_crud_route('common-question','CommonQuestionController');

    create_crud_route('sellers/{seller_id}/messages', 'UserMessageController',['edit','update'],['names'=>'seller.message']);
    Route::put('sellers/{seller_id}/messages/{message_id}', 'Admin\UserMessageController@addAnswer');


    create_crud_route('users/{user_id}/messages', 'UserMessageController',['edit','update'],['names'=>'user.message']);
    Route::put('users/{user_id}/messages/{message_id}', 'Admin\UserMessageController@addAnswer')->name('user.message.answer');


    create_crud_route('messages', 'MessageController',['edit','update','create','store']);
    Route::put('messages/addAnswer/{id}','Admin\MessageController@addAnswer');

    create_crud_route('comments','CommentController',['show','create','store','edit','update']);
    Route::post('comment/change_status','Admin\CommentController@change_status')->name('comment_change_status');

    create_crud_route('questions','QuestionController',['show','create','store','edit','update']);
    Route::post('question/change_status','Admin\QuestionController@change_status')->name('change_question_status');
    Route::post('question/addAnswer/{id}','Admin\QuestionController@addAnswer')->name('questions_addAnswer');

    Route::get('product/review/primary','Admin\ReviewController@primary');
    Route::post('product/review/primary','Admin\ReviewController@add_primary_content');
    create_crud_route('product/review','ReviewController');

    create_crud_route('userRole','UserRoleController');
    Route::get('userRole/access/{role_id}','Admin\UserRoleController@access');
    Route::post('userRole/access/{role_id}','Admin\UserRoleController@add_access');
    create_crud_route('users','UsersController',[]);

    create_crud_route('sellers', 'SellerController',['create','store']);
    Route::get('seller/pay/export', 'Admin\SellerController@export');
    Route::get('seller/pay/import', 'Admin\SellerController@import');
    Route::post('seller/pay/import', 'Admin\SellerController@add_payment');

    create_crud_route('orders','OrdersController',['create','store','edit','update']);
    Route::get('orders/submission','Admin\OrdersController@submission')->name('orders.submissions');
    Route::get('orders/submission/approved','Admin\OrdersController@submission_approved')->name('orders.submission_approved');
    Route::get('orders/submission/items/today','Admin\OrdersController@items_today')->name('orders.items_today');
    Route::get('orders/submission/ready','Admin\OrdersController@submission_ready')->name('orders.submissions_ready');
    Route::get('orders/posting/send','Admin\OrdersController@posting_send')->name('orders.postings_sent');
    Route::get('orders/posting/receive','Admin\OrdersController@posting_receive')->name('orders.postings_receive');
    Route::get('orders/delivered/shipping','Admin\OrdersController@delivered_shipping')->name('orders.delivered_shipping');
    Route::get('orders/submission/{submission_id}','Admin\OrdersController@submission_info')->name('submissions_info');
    Route::get('orders/return-product','Admin\OrdersController@return_product_list')->name('orders.return-product-list');
    Route::post('orders/return-product','Admin\OrdersController@remove_return_product')->name('orders.remove-return-product');
    Route::post('order/change_status','Admin\OrdersController@change_status')->name('order.change_status');
    Route::get('orders/submission/factor/{submission_id}','Admin\OrdersController@submission_foctor')->name('submissions_factor');
    Route::get('orders/return-product/{id}','Admin\OrdersController@return_product')->name('return-product');
    Route::post('orders/return-product/{id}','Admin\OrdersController@add_return_product')->name('return-product');

    Route::get('products/gallery/{id}','Admin\ProductController@gallery');
    Route::post('products/gallery_upload/{id}','Admin\ProductController@gallery_upload');
    Route::delete('products/gallery/{id}','Admin\ProductController@removeImageGallery');
    Route::post('products/change_images_status/{id}','Admin\ProductController@change_images_status');
    Route::get('products/{id}/items','Admin\ProductController@items');
    Route::post('products/{id}/items','Admin\ProductController@add_items');
    Route::get('products/{id}/filters','Admin\ProductController@filters');
    Route::post('products/{id}/filters','Admin\ProductController@add_filters');

    Route::get('category/{id}/items','Admin\ItemController@items');
    Route::post('category/{id}/item','Admin\ItemController@add_items');
    Route::delete('category/items/{id}','Admin\ItemController@destroy');

    Route::get('category/{id}/filters','Admin\FilterController@filters');
    Route::post('category/{id}/filters','Admin\FilterController@add_filters');
    Route::delete('category/filters/{id}','Admin\FilterController@destroy');

    Route::get('category/{id}/price_variation','Admin\PriceVariationController@priceVariation');
    Route::post('category/{id}/price_variation','Admin\PriceVariationController@add_price_variation');
    Route::delete('category/price_variation/{id}','Admin\PriceVariationController@destroy');

    Route::get('incredible-offers','Admin\AdminController@incredible_offers')->name('incredible_offers');
    Route::get('ajax/getWarranty','Admin\AdminController@getWarranty')->name('ajaxGetWarranty');
    Route::post('add_incredible_offers/{warranty_id}','Admin\AdminController@add_incredible_offers')->name('add_incredible_offers');
    Route::post('remove_incredible_offers/{warranty_id}','Admin\AdminController@remove_incredible_offers')->name('remove_incredible_offers');

    Route::match(['get','post'],'setting/send-order-price','Admin\SettingController@send_order_price');
    Route::match(['get','post'],'setting/shop','Admin\SettingController@shop');
    Route::match(['get','post'],'setting/payment-gateway','Admin\SettingController@payment_gateway');

    Route::get('stockroom/input','Admin\StockroomController@input')->name('stockroom.input');
    Route::get('stockroom/input/{id}','Admin\StockroomController@show_input')->name('stockroom.show_input');
    Route::post('stockroom/add_product','Admin\StockroomController@add_product')->name('stockroom.add_product');
    Route::get('stockroom/add/input','Admin\StockroomController@add_input')->name('stockroom.add_input');

    Route::get('stockroom/output','Admin\StockroomController@output')->name('stockroom.output');
    Route::get('stockroom/output/{id}','Admin\StockroomController@show_output')->name('stockroom.show_output');
    Route::post('stockroom/add_output','Admin\StockroomController@add_product')->name('stockroom.add_product');
    Route::get('stockroom/add/output','Admin\StockroomController@add_output')->name('stockroom.add_output');
    Route::get('factor/{id}/input','Admin\StockroomController@input_factor')->name('stockroom.input_factor');
    Route::get('factor/{id}/output','Admin\StockroomController@output_factor')->name('stockroom.output_factor');

    create_crud_route('packages','PackageController',['create','store','edit','update']);
    Route::get('package/getContent/{id}','Admin\PackageController@getContent');
    Route::post('package/stockroom/add_product','Admin\PackageController@add_product');

    create_crud_route('stockrooms','StockroomController',[]);
    Route::get('stockroom/getProductWarrnty','Admin\StockroomController@getProductWarrnty')->name('get_product_warrnty');
    Route::get('stockroom/getInventory','Admin\StockroomController@getInventory')->name('get_inventory');
    Route::get('report/sale','Admin\AdminController@sale_report')->name('sale_report');
    Route::get('shop/get_sale_report','Admin\AdminController@get_sale_report')->name('get_sale_report');
    Route::get('product/get_sale_report','Admin\ProductController@get_sale_report');
});



Route::get('/', 'SiteController@index');
Route::get('sitemap-category.xml','SiteController@sitemap_category');
Route::get('sitemap.xml','SiteController@sitemap');
Route::get('products/{page}/sitemap-products.xml','SiteController@sitemap_products');
Route::get('/faq', 'SiteController@faq');

Route::get('search','SiteController@search_product');
Route::get('getProduct/search','SiteController@get_search_product');

app/UserRole.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class UserRole extends Model
{
    use SoftDeletes;
    protected $fillable=['name'];
    public static function getData($request)
    {
        $string='?';
        $userRole=self::withCount('userrole')->orderBy('id','DESC');
        if(inTrashed($request))
        {
            $userRole=$userRole->onlyTrashed();
            $string=create_paginate_url($string,'trashed=true');
        }
        $userRole=$userRole->paginate(10);
        $userRole->withPath($string);
        return $userRole;
    }
    public function userrole()
    {
        return $this->hasMany(User::class,'role_id','id');
    }
}

app/Http/Controllers/Admin/UserRoleController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\UserRole;
use DB;
class UserRoleController extends CustomController
{
    protected  $model='UserRole';
    protected  $title='نقش کاربری';
    protected $route_params='userRole';
    public function index(Request $request)
    {
        $userRole=UserRole::getData($request->all());
        $trash_role_count=UserRole::onlyTrashed()->count();
        return view('userRole.index',['userRole'=>$userRole,'trash_role_count'=>$trash_role_count,'req'=>$request]);
    }
    public function create()
    {
        return view('userRole.create');
    }
    public function store(Request $request)
    {
        $this->validate($request,['name'=>'required|unique:user_roles'],[],['role_name'=>'نام نقش کاربری']);
        $userRole=new UserRole($request->all());
        $userRole->saveOrFail();
        return redirect('admin/userRole')->with('message','ثبت نقش کاربری با موفقیت انجام شد');
    }
    public function edit($id)
    {
        $userRole=UserRole::findOrFail($id);
        return view('userRole.edit',['userRole'=>$userRole]);
    }
    public function update($id,Request $request)
    {
        $this->validate($request,['name'=>'required|unique:user_roles,name,'.$id],[],['role_name'=>'نام نقش کاربری']);
        $userRole=UserRole::findOrFail($id);
        $userRole->update($request->all());
        return redirect('admin/userRole')->with('message','ویرایش نقش کاربری با موفقیت انجام شد');
    }
    public function access($role_id)
    {
        $role=UserRole::findOrFail($role_id);
        $role_accesses=DB::table('role_accesses')->where('role_id',$role_id)->first();
        return view('userRole.access',['role'=>$role,'role_accesses'=>$role_accesses]);
    }
    public function add_access($role_id,Request $request)
    {
        $role=UserRole::findOrFail($role_id);
        $access=$request->get('access',array());
        DB::table('role_accesses')->where('role_id',$role_id)->delete();

        $string=json_encode($access);
        DB::table('role_accesses')->insert(['role_id'=>$role_id,'access'=>$string]);
        return redirect()->back()->with('message','ثبت دسترسی با موفقیت انجام شد');
    }
}

resources/views/userRole/access.blade.php
@extends('layouts.admin')

@section('content')

    @include('include.breadcrumb',['data'=>[
         ['title'=>'مدیریت نقش های کاربری','url'=>url('admin/userRole')],
         ['title'=>'تعیین دسترسی های نقش : '.$role->name,'url'=>url('admin/userRole/access/'.$role->id)]
    ]])
    <div class="panel">
        <div class="header">تعیین دسترسی های نقش : {{ $role->name }}</div>

        @php
            $AccessList=\App\User::AccessList();
        @endphp
        <div class="panel_content">
            @include('include.Alert')
            <form method="POST">
                @csrf
                <ul class="access">
                    @foreach ($AccessList as $key=>$item)
                        <li class="item_groups" style="margin-bottm:20px">
                            <span>{{ $item['label'] }}</span>
                            <ul>
                                @foreach ($item['access'] as $key2=>$value2)
                                    <li>
                                        <input type="checkbox" @if(CheckAccess($role_accesses,$key,$key2)) checked="checked" @endif name="access[{{ $key }}][]" value="{{ $key2 }}">
                                        {{ $value2['label'] }}
                                    </li>
                                @endforeach
                            </ul>
                        </li>
                    @endforeach
                </ul>

                <div class="form-group">
                    <button class="btn btn-success">ثبت</button>
                </div>
            </form>
        </div>
    </div>
@endsection    

resources/views/userRole/create.blade.php
@extends('layouts.admin')

@section('content')

    @include('include.breadcrumb',['data'=>[
         ['title'=>'مدیریت نقش های کاربری','url'=>url('admin/userRole')],
         ['title'=>'افزودن نقش کاربری جدید','url'=>url('admin/userRole/create')]
    ]])
    <div class="panel">
        <div class="header">افزودن نقش کاربری جدید</div>

        <div class="panel_content">

            {!! Form::open(['url' => 'admin/userRole']) !!}

            <div class="form-group">

                {{ Form::label('name','نام نقش کاربری : ') }}
                {{ Form::text('name',null,['class'=>'form-control']) }}
                @if($errors->has('name'))
                    <span class="has_error">{{ $errors->first('name') }}</span>
                @endif
            </div>

            <button class="btn btn-success">ثبت</button>
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/userRole/edit.blade.php
@extends('layouts.admin')

@section('content')

    @include('include.breadcrumb',['data'=>[
         ['title'=>'مدیریت نقش های کاربری','url'=>url('admin/userRole')],
         ['title'=>'ویرایش نقش کاربری','url'=>url('admin/userRole/'.$userRole->id.'/edit')]
    ]])

    <div class="panel">

        <div class="header">ویرایش نقش کاربری - {{ $userRole->name }}</div>

        <div class="panel_content">


            {!! Form::model($userRole,['url' => 'admin/userRole/'.$userRole->id]) !!}

            {{ method_field('put') }}
            <div class="form-group">

                {{ Form::label('name','نام نقش کاربری : ') }}
                {{ Form::text('name',null,['class'=>'form-control']) }}
                @if($errors->has('name'))
                    <span class="has_error">{{ $errors->first('name') }}</span>
                @endif
            </div>

            <button class="btn btn-primary">ویرایش</button>
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/userRole/index.blade.php
@extends('layouts.admin')

@section('content')

    @include('include.breadcrumb',['data'=>[['title'=>'مدیریت نقش های کاربری','url'=>url('admin/userRole')]]])
    <div class="panel">

        <div class="header">
            مدیریت نقش های کاربری

            @include('include.item_table',['count'=>$trash_role_count,'route'=>'admin/userRole','title'=>'نقش کاربری'])
        </div>

        <div class="panel_content">

            @include('include.Alert')
            <?php $i=(isset($_GET['page'])) ? (($_GET['page']-1)*10): 0 ; ?>

         
            <form method="post" id="data_form">
                @csrf
                <table class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>ردیف</th>
                        <th>نام نقش</th>
                        <th>تعداد کاربر</th>
                        <th>عمیات</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($userRole as $key=>$value)
                        @php $i++; @endphp
                        <tr>
                            <td>
                                <input type="checkbox" name="userRole_id[]" class="check_box" value="{{ $value->id }}"/>
                            </td>
                            <td>{{ replace_number($i) }}</td>
                            <td>{{ $value->name }}</td>
                            <td>{{ replace_number($value->userrole_count) }}</td>
                            <td>
                                @if(!$value->trashed())
                                <a href="{{ url('admin/userRole/'.$value->id.'/edit') }}"><span class="fa fa-edit"></span></a>
                                @endif

                                <a href="{{ url('admin/userRole/access/'.$value->id) }}" style="color:black">
                                    <span  data-toggle="tooltip" data-placement="bottom"  title='دسترسی ها'  class="fa fa-lock"></span>
                                </a>

                                @if($value->trashed())
                                   <span  data-toggle="tooltip" data-placement="bottom"  title='بازیابی نقش کاربری' onclick="restore_row('{{ url('admin/userRole/'.$value->id) }}','{{ Session::token() }}','آیا از بازیابی این نقش کاربری مطمئن هستین ؟ ')" class="fa fa-refresh"></span>
                                @endif

                                @if(!$value->trashed())
                                <span data-toggle="tooltip" data-placement="bottom"  title='حذف نقش کاربری' onclick="del_row('{{ url('admin/userRole/'.$value->id) }}','{{ Session::token() }}','آیا از حذف این نقش کاربری مطمئن هستین ؟ ')" class="fa fa-remove"></span>
                                @else
                                <span data-toggle="tooltip" data-placement="bottom"  title='حذف نقش کاربری برای همیشه' onclick="del_row('{{ url('admin/userRole/'.$value->id) }}','{{ Session::token() }}','آیا از حذف این نقش کاربری مطمئن هستین ؟ ')" class="fa fa-remove"></span>
                                 @endif
                            </td>
                        </tr>

                    @endforeach

                    @if(sizeof($userRole)==0)
                        <tr>
                            <td colspan="5">رکوردی برای نمایش وجود ندارد</td>
                        </tr>
                    @endif
                    </tbody>
                </table>
            </form>

            {{ $userRole->links() }}
        </div>
    </div>

@endsection